package com.airdropaddict.webpage.shared.data;

import java.io.Serializable;

/**
 * Access data is an information about user.
 * User can be identified on certain levels:
 *  - by ip - if no other info about user is given, IP is the only thing that identifies user
 *  - by token - if token (cookie) was generated by system, it can identify user regardless of IP he is using
 *  - by user - if user has signed it, he / she is identified regardless of IP or token he is using
 */
public class AccessData implements Serializable {
    private UserData user;
    private String token;
    private String ip;

    public UserData getUser() {
        return user;
    }

    public void setUser(UserData user) {
        this.user = user;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }
}
